// src/components/GojuonMachine/kanaData.js

export const KANA_LIST = [
  { kana: 'あ', romaji: ['a'], type: '平假名' },
  { kana: 'い', romaji: ['i'], type: '平假名' },
  { kana: 'う', romaji: ['u'], type: '平假名' },
  { kana: 'え', romaji: ['e'], type: '平假名' },
  { kana: 'お', romaji: ['o'], type: '平假名' },
  { kana: 'か', romaji: ['ka'], type: '平假名' },
  { kana: 'き', romaji: ['ki'], type: '平假名' },
  { kana: 'く', romaji: ['ku'], type: '平假名' },
  { kana: 'け', romaji: ['ke'], type: '平假名' },
  { kana: 'こ', romaji: ['ko'], type: '平假名' },
  { kana: 'さ', romaji: ['sa'], type: '平假名' },
  { kana: 'し', romaji: ['shi', 'si'], type: '平假名' },
  { kana: 'す', romaji: ['su'], type: '平假名' },
  { kana: 'せ', romaji: ['se'], type: '平假名' },
  { kana: 'そ', romaji: ['so'], type: '平假名' },
  { kana: 'た', romaji: ['ta'], type: '平假名' },
  { kana: 'ち', romaji: ['chi', 'ti'], type: '平假名' },
  { kana: 'つ', romaji: ['tsu', 'tu'], type: '平假名' },
  { kana: 'て', romaji: ['te'], type: '平假名' },
  { kana: 'と', romaji: ['to'], type: '平假名' },
  { kana: 'な', romaji: ['na'], type: '平假名' },
  { kana: 'に', romaji: ['ni'], type: '平假名' },
  { kana: 'ぬ', romaji: ['nu'], type: '平假名' },
  { kana: 'ね', romaji: ['ne'], type: '平假名' },
  { kana: 'の', romaji: ['no'], type: '平假名' },
  { kana: 'は', romaji: ['ha'], type: '平假名' },
  { kana: 'ひ', romaji: ['hi'], type: '平假名' },
  { kana: 'ふ', romaji: ['fu', 'hu'], type: '平假名' },
  { kana: 'へ', romaji: ['he'], type: '平假名' },
  { kana: 'ほ', romaji: ['ho'], type: '平假名' },
  { kana: 'ま', romaji: ['ma'], type: '平假名' },
  { kana: 'み', romaji: ['mi'], type: '平假名' },
  { kana: 'む', romaji: ['mu'], type: '平假名' },
  { kana: 'め', romaji: ['me'], type: '平假名' },
  { kana: 'も', romaji: ['mo'], type: '平假名' },
  { kana: 'や', romaji: ['ya'], type: '平假名' },
  { kana: 'ゆ', romaji: ['yu'], type: '平假名' },
  { kana: 'よ', romaji: ['yo'], type: '平假名' },
  { kana: 'ら', romaji: ['ra'], type: '平假名' },
  { kana: 'り', romaji: ['ri'], type: '平假名' },
  { kana: 'る', romaji: ['ru'], type: '平假名' },
  { kana: 'れ', romaji: ['re'], type: '平假名' },
  { kana: 'ろ', romaji: ['ro'], type: '平假名' },
  { kana: 'わ', romaji: ['wa'], type: '平假名' },
  { kana: 'を', romaji: ['wo', 'o'], type: '平假名' },
  { kana: 'ん', romaji: ['n'], type: '平假名' },
  { kana: 'ア', romaji: ['a'], type: '片假名' },
  { kana: 'イ', romaji: ['i'], type: '片假名' },
  { kana: 'ウ', romaji: ['u'], type: '片假名' },
  { kana: 'エ', romaji: ['e'], type: '片假名' },
  { kana: 'オ', romaji: ['o'], type: '片假名' },
  { kana: 'カ', romaji: ['ka'], type: '片假名' },
  { kana: 'キ', romaji: ['ki'], type: '片假名' },
  { kana: 'ク', romaji: ['ku'], type: '片假名' },
  { kana: 'ケ', romaji: ['ke'], type: '片假名' },
  { kana: 'コ', romaji: ['ko'], type: '片假名' },
  { kana: 'サ', romaji: ['sa'], type: '片假名' },
  { kana: 'シ', romaji: ['shi', 'si'], type: '片假名' },
  { kana: 'ス', romaji: ['su'], type: '片假名' },
  { kana: 'セ', romaji: ['se'], type: '片假名' },
  { kana: 'ソ', romaji: ['so'], type: '片假名' },
  { kana: 'タ', romaji: ['ta'], type: '片假名' },
  { kana: 'チ', romaji: ['chi', 'ti'], type: '片假名' },
  { kana: 'ツ', romaji: ['tsu', 'tu'], type: '片假名' },
  { kana: 'テ', romaji: ['te'], type: '片假名' },
  { kana: 'ト', romaji: ['to'], type: '片假名' },
  { kana: 'ナ', romaji: ['na'], type: '片假名' },
  { kana: 'ニ', romaji: ['ni'], type: '片假名' },
  { kana: 'ヌ', romaji: ['nu'], type: '片假名' },
  { kana: 'ネ', romaji: ['ne'], type: '片假名' },
  { kana: 'ノ', romaji: ['no'], type: '片假名' },
  { kana: 'ハ', romaji: ['ha'], type: '片假名' },
  { kana: 'ヒ', romaji: ['hi'], type: '片假名' },
  { kana: 'フ', romaji: ['fu', 'hu'], type: '片假名' },
  { kana: 'ヘ', romaji: ['he'], type: '片假名' },
  { kana: 'ホ', romaji: ['ho'], type: '片假名' },
  { kana: 'マ', romaji: ['ma'], type: '片假名' },
  { kana: 'ミ', romaji: ['mi'], type: '片假名' },
  { kana: 'ム', romaji: ['mu'], type: '片假名' },
  { kana: 'メ', romaji: ['me'], type: '片假名' },
  { kana: 'モ', romaji: ['mo'], type: '片假名' },
  { kana: 'ヤ', romaji: ['ya'], type: '片假名' },
  { kana: 'ユ', romaji: ['yu'], type: '片假名' },
  { kana: 'ヨ', romaji: ['yo'], type: '片假名' },
  { kana: 'ラ', romaji: ['ra'], type: '片假名' },
  { kana: 'リ', romaji: ['ri'], type: '片假名' },
  { kana: 'ル', romaji: ['ru'], type: '片假名' },
  { kana: 'レ', romaji: ['re'], type: '片假名' },
  { kana: 'ロ', romaji: ['ro'], type: '片假名' },
  { kana: 'ワ', romaji: ['wa'], type: '片假名' },
  { kana: 'ヲ', romaji: ['wo', 'o'], type: '片假名' },
  { kana: 'ン', romaji: ['n'], type: '片假名' }
]
