// src/components/GojuonMachine/kanaData.js

export const KANA_LIST = [
  // 清音 - 平假名
  { kana: 'あ', romaji: ['a'], type: '平假名', group: '清音' },
  { kana: 'い', romaji: ['i'], type: '平假名', group: '清音' },
  { kana: 'う', romaji: ['u'], type: '平假名', group: '清音' },
  { kana: 'え', romaji: ['e'], type: '平假名', group: '清音' },
  { kana: 'お', romaji: ['o'], type: '平假名', group: '清音' },
  { kana: 'か', romaji: ['ka'], type: '平假名', group: '清音' },
  { kana: 'き', romaji: ['ki'], type: '平假名', group: '清音' },
  { kana: 'く', romaji: ['ku'], type: '平假名', group: '清音' },
  { kana: 'け', romaji: ['ke'], type: '平假名', group: '清音' },
  { kana: 'こ', romaji: ['ko'], type: '平假名', group: '清音' },
  { kana: 'さ', romaji: ['sa'], type: '平假名', group: '清音' },
  { kana: 'し', romaji: ['shi', 'si'], type: '平假名', group: '清音' },
  { kana: 'す', romaji: ['su'], type: '平假名', group: '清音' },
  { kana: 'せ', romaji: ['se'], type: '平假名', group: '清音' },
  { kana: 'そ', romaji: ['so'], type: '平假名', group: '清音' },
  { kana: 'た', romaji: ['ta'], type: '平假名', group: '清音' },
  { kana: 'ち', romaji: ['chi', 'ti'], type: '平假名', group: '清音' },
  { kana: 'つ', romaji: ['tsu', 'tu'], type: '平假名', group: '清音' },
  { kana: 'て', romaji: ['te'], type: '平假名', group: '清音' },
  { kana: 'と', romaji: ['to'], type: '平假名', group: '清音' },
  { kana: 'な', romaji: ['na'], type: '平假名', group: '清音' },
  { kana: 'に', romaji: ['ni'], type: '平假名', group: '清音' },
  { kana: 'ぬ', romaji: ['nu'], type: '平假名', group: '清音' },
  { kana: 'ね', romaji: ['ne'], type: '平假名', group: '清音' },
  { kana: 'の', romaji: ['no'], type: '平假名', group: '清音' },
  { kana: 'は', romaji: ['ha'], type: '平假名', group: '清音' },
  { kana: 'ひ', romaji: ['hi'], type: '平假名', group: '清音' },
  { kana: 'ふ', romaji: ['fu', 'hu'], type: '平假名', group: '清音' },
  { kana: 'へ', romaji: ['he'], type: '平假名', group: '清音' },
  { kana: 'ほ', romaji: ['ho'], type: '平假名', group: '清音' },
  { kana: 'ま', romaji: ['ma'], type: '平假名', group: '清音' },
  { kana: 'み', romaji: ['mi'], type: '平假名', group: '清音' },
  { kana: 'む', romaji: ['mu'], type: '平假名', group: '清音' },
  { kana: 'め', romaji: ['me'], type: '平假名', group: '清音' },
  { kana: 'も', romaji: ['mo'], type: '平假名', group: '清音' },
  { kana: 'や', romaji: ['ya'], type: '平假名', group: '清音' },
  { kana: 'ゆ', romaji: ['yu'], type: '平假名', group: '清音' },
  { kana: 'よ', romaji: ['yo'], type: '平假名', group: '清音' },
  { kana: 'ら', romaji: ['ra'], type: '平假名', group: '清音' },
  { kana: 'り', romaji: ['ri'], type: '平假名', group: '清音' },
  { kana: 'る', romaji: ['ru'], type: '平假名', group: '清音' },
  { kana: 'れ', romaji: ['re'], type: '平假名', group: '清音' },
  { kana: 'ろ', romaji: ['ro'], type: '平假名', group: '清音' },
  { kana: 'わ', romaji: ['wa'], type: '平假名', group: '清音' },
  { kana: 'を', romaji: ['wo', 'o'], type: '平假名', group: '清音' },
  { kana: 'ん', romaji: ['n'], type: '平假名', group: '清音' },

  // 濁音 - 平假名
  { kana: 'が', romaji: ['ga'], type: '平假名', group: '濁音' },
  { kana: 'ぎ', romaji: ['gi'], type: '平假名', group: '濁音' },
  { kana: 'ぐ', romaji: ['gu'], type: '平假名', group: '濁音' },
  { kana: 'げ', romaji: ['ge'], type: '平假名', group: '濁音' },
  { kana: 'ご', romaji: ['go'], type: '平假名', group: '濁音' },
  { kana: 'ざ', romaji: ['za'], type: '平假名', group: '濁音' },
  { kana: 'じ', romaji: ['ji', 'zi'], type: '平假名', group: '濁音' },
  { kana: 'ず', romaji: ['zu'], type: '平假名', group: '濁音' },
  { kana: 'ぜ', romaji: ['ze'], type: '平假名', group: '濁音' },
  { kana: 'ぞ', romaji: ['zo'], type: '平假名', group: '濁音' },
  { kana: 'だ', romaji: ['da'], type: '平假名', group: '濁音' },
  { kana: 'ぢ', romaji: ['ji', 'di'], type: '平假名', group: '濁音' },
  { kana: 'づ', romaji: ['zu', 'du'], type: '平假名', group: '濁音' },
  { kana: 'で', romaji: ['de'], type: '平假名', group: '濁音' },
  { kana: 'ど', romaji: ['do'], type: '平假名', group: '濁音' },
  { kana: 'ば', romaji: ['ba'], type: '平假名', group: '濁音' },
  { kana: 'び', romaji: ['bi'], type: '平假名', group: '濁音' },
  { kana: 'ぶ', romaji: ['bu'], type: '平假名', group: '濁音' },
  { kana: 'べ', romaji: ['be'], type: '平假名', group: '濁音' },
  { kana: 'ぼ', romaji: ['bo'], type: '平假名', group: '濁音' },

  // 半濁音 - 平假名
  { kana: 'ぱ', romaji: ['pa'], type: '平假名', group: '半濁音' },
  { kana: 'ぴ', romaji: ['pi'], type: '平假名', group: '半濁音' },
  { kana: 'ぷ', romaji: ['pu'], type: '平假名', group: '半濁音' },
  { kana: 'ぺ', romaji: ['pe'], type: '平假名', group: '半濁音' },
  { kana: 'ぽ', romaji: ['po'], type: '平假名', group: '半濁音' },

  // 拗音 - 平假名
  { kana: 'きゃ', romaji: ['kya'], type: '平假名', group: '拗音' },
  { kana: 'きゅ', romaji: ['kyu'], type: '平假名', group: '拗音' },
  { kana: 'きょ', romaji: ['kyo'], type: '平假名', group: '拗音' },
  { kana: 'しゃ', romaji: ['sha', 'sya'], type: '平假名', group: '拗音' },
  { kana: 'しゅ', romaji: ['shu', 'syu'], type: '平假名', group: '拗音' },
  { kana: 'しょ', romaji: ['sho', 'syo'], type: '平假名', group: '拗音' },
  {
    kana: 'ちゃ',
    romaji: ['cha', 'tya', 'cya'],
    type: '平假名',
    group: '拗音'
  },
  {
    kana: 'ちゅ',
    romaji: ['chu', 'tyu', 'cyu'],
    type: '平假名',
    group: '拗音'
  },
  {
    kana: 'ちょ',
    romaji: ['cho', 'tyo', 'cyo'],
    type: '平假名',
    group: '拗音'
  },
  { kana: 'にゃ', romaji: ['nya'], type: '平假名', group: '拗音' },
  { kana: 'にゅ', romaji: ['nyu'], type: '平假名', group: '拗音' },
  { kana: 'にょ', romaji: ['nyo'], type: '平假名', group: '拗音' },
  { kana: 'ひゃ', romaji: ['hya'], type: '平假名', group: '拗音' },
  { kana: 'ひゅ', romaji: ['hyu'], type: '平假名', group: '拗音' },
  { kana: 'ひょ', romaji: ['hyo'], type: '平假名', group: '拗音' },
  { kana: 'みゃ', romaji: ['mya'], type: '平假名', group: '拗音' },
  { kana: 'みゅ', romaji: ['myu'], type: '平假名', group: '拗音' },
  { kana: 'みょ', romaji: ['myo'], type: '平假名', group: '拗音' },
  { kana: 'りゃ', romaji: ['rya'], type: '平假名', group: '拗音' },
  { kana: 'りゅ', romaji: ['ryu'], type: '平假名', group: '拗音' },
  { kana: 'りょ', romaji: ['ryo'], type: '平假名', group: '拗音' },
  { kana: 'ぎゃ', romaji: ['gya'], type: '平假名', group: '拗音' },
  { kana: 'ぎゅ', romaji: ['gyu'], type: '平假名', group: '拗音' },
  { kana: 'ぎょ', romaji: ['gyo'], type: '平假名', group: '拗音' },
  { kana: 'じゃ', romaji: ['ja', 'jya', 'zya'], type: '平假名', group: '拗音' },
  { kana: 'じゅ', romaji: ['ju', 'jyu', 'zyu'], type: '平假名', group: '拗音' },
  { kana: 'じょ', romaji: ['jo', 'jyo', 'zyo'], type: '平假名', group: '拗音' },
  { kana: 'びゃ', romaji: ['bya'], type: '平假名', group: '拗音' },
  { kana: 'びゅ', romaji: ['byu'], type: '平假名', group: '拗音' },
  { kana: 'びょ', romaji: ['byo'], type: '平假名', group: '拗音' },
  { kana: 'ぴゃ', romaji: ['pya'], type: '平假名', group: '拗音' },
  { kana: 'ぴゅ', romaji: ['pyu'], type: '平假名', group: '拗音' },
  { kana: 'ぴょ', romaji: ['pyo'], type: '平假名', group: '拗音' },

  // 清音 - 片假名
  { kana: 'ア', romaji: ['a'], type: '片假名', group: '清音' },
  { kana: 'イ', romaji: ['i'], type: '片假名', group: '清音' },
  { kana: 'ウ', romaji: ['u'], type: '片假名', group: '清音' },
  { kana: 'エ', romaji: ['e'], type: '片假名', group: '清音' },
  { kana: 'オ', romaji: ['o'], type: '片假名', group: '清音' },
  { kana: 'カ', romaji: ['ka'], type: '片假名', group: '清音' },
  { kana: 'キ', romaji: ['ki'], type: '片假名', group: '清音' },
  { kana: 'ク', romaji: ['ku'], type: '片假名', group: '清音' },
  { kana: 'ケ', romaji: ['ke'], type: '片假名', group: '清音' },
  { kana: 'コ', romaji: ['ko'], type: '片假名', group: '清音' },
  { kana: 'サ', romaji: ['sa'], type: '片假名', group: '清音' },
  { kana: 'シ', romaji: ['shi', 'si'], type: '片假名', group: '清音' },
  { kana: 'ス', romaji: ['su'], type: '片假名', group: '清音' },
  { kana: 'セ', romaji: ['se'], type: '片假名', group: '清音' },
  { kana: 'ソ', romaji: ['so'], type: '片假名', group: '清音' },
  { kana: 'タ', romaji: ['ta'], type: '片假名', group: '清音' },
  { kana: 'チ', romaji: ['chi', 'ti'], type: '片假名', group: '清音' },
  { kana: 'ツ', romaji: ['tsu', 'tu'], type: '片假名', group: '清音' },
  { kana: 'テ', romaji: ['te'], type: '片假名', group: '清音' },
  { kana: 'ト', romaji: ['to'], type: '片假名', group: '清音' },
  { kana: 'ナ', romaji: ['na'], type: '片假名', group: '清音' },
  { kana: 'ニ', romaji: ['ni'], type: '片假名', group: '清音' },
  { kana: 'ヌ', romaji: ['nu'], type: '片假名', group: '清音' },
  { kana: 'ネ', romaji: ['ne'], type: '片假名', group: '清音' },
  { kana: 'ノ', romaji: ['no'], type: '片假名', group: '清音' },
  { kana: 'ハ', romaji: ['ha'], type: '片假名', group: '清音' },
  { kana: 'ヒ', romaji: ['hi'], type: '片假名', group: '清音' },
  { kana: 'フ', romaji: ['fu', 'hu'], type: '片假名', group: '清音' },
  { kana: 'ヘ', romaji: ['he'], type: '片假名', group: '清音' },
  { kana: 'ホ', romaji: ['ho'], type: '片假名', group: '清音' },
  { kana: 'マ', romaji: ['ma'], type: '片假名', group: '清音' },
  { kana: 'ミ', romaji: ['mi'], type: '片假名', group: '清音' },
  { kana: 'ム', romaji: ['mu'], type: '片假名', group: '清音' },
  { kana: 'メ', romaji: ['me'], type: '片假名', group: '清音' },
  { kana: 'モ', romaji: ['mo'], type: '片假名', group: '清音' },
  { kana: 'ヤ', romaji: ['ya'], type: '片假名', group: '清音' },
  { kana: 'ユ', romaji: ['yu'], type: '片假名', group: '清音' },
  { kana: 'ヨ', romaji: ['yo'], type: '片假名', group: '清音' },
  { kana: 'ラ', romaji: ['ra'], type: '片假名', group: '清音' },
  { kana: 'リ', romaji: ['ri'], type: '片假名', group: '清音' },
  { kana: 'ル', romaji: ['ru'], type: '片假名', group: '清音' },
  { kana: 'レ', romaji: ['re'], type: '片假名', group: '清音' },
  { kana: 'ロ', romaji: ['ro'], type: '片假名', group: '清音' },
  { kana: 'ワ', romaji: ['wa'], type: '片假名', group: '清音' },
  { kana: 'ヲ', romaji: ['wo', 'o'], type: '片假名', group: '清音' },
  { kana: 'ン', romaji: ['n'], type: '片假名', group: '清音' },

  // 濁音 - 片假名
  { kana: 'ガ', romaji: ['ga'], type: '片假名', group: '濁音' },
  { kana: 'ギ', romaji: ['gi'], type: '片假名', group: '濁音' },
  { kana: 'グ', romaji: ['gu'], type: '片假名', group: '濁音' },
  { kana: 'ゲ', romaji: ['ge'], type: '片假名', group: '濁音' },
  { kana: 'ゴ', romaji: ['go'], type: '片假名', group: '濁音' },
  { kana: 'ザ', romaji: ['za'], type: '片假名', group: '濁音' },
  { kana: 'ジ', romaji: ['ji', 'zi'], type: '片假名', group: '濁音' },
  { kana: 'ズ', romaji: ['zu'], type: '片假名', group: '濁音' },
  { kana: 'ゼ', romaji: ['ze'], type: '片假名', group: '濁音' },
  { kana: 'ゾ', romaji: ['zo'], type: '片假名', group: '濁音' },
  { kana: 'ダ', romaji: ['da'], type: '片假名', group: '濁音' },
  { kana: 'ヂ', romaji: ['ji', 'di'], type: '片假名', group: '濁音' },
  { kana: 'ヅ', romaji: ['zu', 'du'], type: '片假名', group: '濁音' },
  { kana: 'デ', romaji: ['de'], type: '片假名', group: '濁音' },
  { kana: 'ド', romaji: ['do'], type: '片假名', group: '濁音' },
  { kana: 'バ', romaji: ['ba'], type: '片假名', group: '濁音' },
  { kana: 'ビ', romaji: ['bi'], type: '片假名', group: '濁音' },
  { kana: 'ブ', romaji: ['bu'], type: '片假名', group: '濁音' },
  { kana: 'ベ', romaji: ['be'], type: '片假名', group: '濁音' },
  { kana: 'ボ', romaji: ['bo'], type: '片假名', group: '濁音' },

  // 半濁音 - 片假名
  { kana: 'パ', romaji: ['pa'], type: '片假名', group: '半濁音' },
  { kana: 'ピ', romaji: ['pi'], type: '片假名', group: '半濁音' },
  { kana: 'プ', romaji: ['pu'], type: '片假名', group: '半濁音' },
  { kana: 'ペ', romaji: ['pe'], type: '片假名', group: '半濁音' },
  { kana: 'ポ', romaji: ['po'], type: '片假名', group: '半濁音' },

  // 拗音 - 片假名
  { kana: 'キャ', romaji: ['kya'], type: '片假名', group: '拗音' },
  { kana: 'キュ', romaji: ['kyu'], type: '片假名', group: '拗音' },
  { kana: 'キョ', romaji: ['kyo'], type: '片假名', group: '拗音' },
  { kana: 'シャ', romaji: ['sha', 'sya'], type: '片假名', group: '拗音' },
  { kana: 'シュ', romaji: ['shu', 'syu'], type: '片假名', group: '拗音' },
  { kana: 'ショ', romaji: ['sho', 'syo'], type: '片假名', group: '拗音' },
  {
    kana: 'チャ',
    romaji: ['cha', 'tya', 'cya'],
    type: '片假名',
    group: '拗音'
  },
  {
    kana: 'チュ',
    romaji: ['chu', 'tyu', 'cyu'],
    type: '片假名',
    group: '拗音'
  },
  {
    kana: 'チョ',
    romaji: ['cho', 'tyo', 'cyo'],
    type: '片假名',
    group: '拗音'
  },
  { kana: 'ニャ', romaji: ['nya'], type: '片假名', group: '拗音' },
  { kana: 'ニュ', romaji: ['nyu'], type: '片假名', group: '拗音' },
  { kana: 'ニョ', romaji: ['nyo'], type: '片假名', group: '拗音' },
  { kana: 'ヒャ', romaji: ['hya'], type: '片假名', group: '拗音' },
  { kana: 'ヒュ', romaji: ['hyu'], type: '片假名', group: '拗音' },
  { kana: 'ヒョ', romaji: ['hyo'], type: '片假名', group: '拗音' },
  { kana: 'ミャ', romaji: ['mya'], type: '片假名', group: '拗音' },
  { kana: 'ミュ', romaji: ['myu'], type: '片假名', group: '拗音' },
  { kana: 'ミョ', romaji: ['myo'], type: '片假名', group: '拗音' },
  { kana: 'リャ', romaji: ['rya'], type: '片假名', group: '拗音' },
  { kana: 'リュ', romaji: ['ryu'], type: '片假名', group: '拗音' },
  { kana: 'リョ', romaji: ['ryo'], type: '片假名', group: '拗音' },
  { kana: 'ギャ', romaji: ['gya'], type: '片假名', group: '拗音' },
  { kana: 'ギュ', romaji: ['gyu'], type: '片假名', group: '拗音' },
  { kana: 'ギョ', romaji: ['gyo'], type: '片假名', group: '拗音' },
  { kana: 'ジャ', romaji: ['ja', 'jya', 'zya'], type: '片假名', group: '拗音' },
  { kana: 'ジュ', romaji: ['ju', 'jyu', 'zyu'], type: '片假名', group: '拗音' },
  { kana: 'ジョ', romaji: ['jo', 'jyo', 'zyo'], type: '片假名', group: '拗音' },
  { kana: 'ビャ', romaji: ['bya'], type: '片假名', group: '拗音' },
  { kana: 'ビュ', romaji: ['byu'], type: '片假名', group: '拗音' },
  { kana: 'ビョ', romaji: ['byo'], type: '片假名', group: '拗音' },
  { kana: 'ピャ', romaji: ['pya'], type: '片假名', group: '拗音' },
  { kana: 'ピュ', romaji: ['pyu'], type: '片假名', group: '拗音' },
  { kana: 'ピョ', romaji: ['pyo'], type: '片假名', group: '拗音' }
]
